name: likebike-backend
app: python@3.11
options:
  env:
    - name: FLASK_ENV
      value: production
    - name: DB_HOST
      value: ${DB_HOST}
    - name: DB_PORT
      value: ${DB_PORT}
    - name: DB_NAME
      value: ${DB_NAME}
    - name: DB_USER
      value: ${DB_USER}
    - name: DB_PASSWORD
      value: ${DB_PASSWORD}
  ports: 3000
  start: gunicorn -b 0.0.0.0:3000 run:app
context:
  git:
    url: https://github.com/HiHoi/LikeBike_backend.git
    branch: dev
  preset: python-flask
