name: flask
app: python@3.11
options:
  env:
    - name: FLASK_ENV
      value: production
  ports: 3000
  start: gunicorn -b 0.0.0.0:3000 app:app
context:
  git:
    url: https://github.com/HiHoi/LikeBike_backend.git
    branch: dev
  preset: python-flask
